services:
  crapuler:
    build: ./apps/crapuler
    restart: unless-stopped
    networks:
      - lobslab
    labels:
      traefik.enable: "true"
      traefik.http.routers.crapuler.rule: "Host(`crapuler.lobslab.com`)"
      traefik.http.routers.crapuler.entrypoints: web
      traefik.http.services.crapuler.loadbalancer.server.port: "4317"

  ballz:
    build: ./apps/ballz
    restart: unless-stopped
    networks:
      - lobslab
    labels:
      traefik.enable: "true"
      traefik.http.routers.ballz.rule: "Host(`ballz.lobslab.com`)"
      traefik.http.routers.ballz.entrypoints: web
      traefik.http.services.ballz.loadbalancer.server.port: "80"

  stellar-siege:
    build: ./apps/stellar-siege
    restart: unless-stopped
    networks:
      - lobslab
    labels:
      traefik.enable: "true"
      traefik.http.routers.stellar-siege.rule: "Host(`stellar-siege.lobslab.com`)"
      traefik.http.routers.stellar-siege.entrypoints: web
      traefik.http.services.stellar-siege.loadbalancer.server.port: "3000"

  ballz-royale:
    build: ./apps/ballz-royale
    restart: unless-stopped
    networks:
      - lobslab
    labels:
      traefik.enable: "true"
      traefik.http.routers.ballz-royale.rule: "Host(`ballz-royale.lobslab.com`)"
      traefik.http.routers.ballz-royale.entrypoints: web
      traefik.http.services.ballz-royale.loadbalancer.server.port: "3000"

  games:
    build: ./apps/games
    restart: unless-stopped
    networks:
      - lobslab
    labels:
      traefik.enable: "true"
      traefik.http.routers.games.rule: "Host(`games.lobslab.com`)"
      traefik.http.routers.games.entrypoints: web
      traefik.http.services.games.loadbalancer.server.port: "3000"

networks:
  lobslab:
    external: true
